### ISSUE TITLE
question about the dataset Semantic Scene Completion dataset (v1.1)

### ISSUE THREAD

**Issue by loki369loki** [Jieqianyu/SSC-RS#2]
Thank you for your excellent work.
Semantic Scene Completion dataset (v1.1)
![d3fd8cb52ca61d88ba57ca3e8d0a436](https://github.com/Jieqianyu/SSC-RS/assets/100119921/210c6b8a-c611-4e68-81d0-069f0c10f2ac)
 Should I download the data represented by 1 or 2 in the image above or both?

**Comment by loki369loki** [comment]
And when I use the data represented by 1 only,I meet the below bug.

2023-07-21 16:24:53,337 -- ============ Validation weights: "weights/weights_epoch_035.pth" ============

=> Parsing SemanticKITTI train
parsing seq 00
parsing seq 01
parsing seq 02
parsing seq 03
parsing seq 04
parsing seq 05
parsing seq 06
parsing seq 07
parsing seq 09
parsing seq 10
Using 3834 scans from sequences [0, 1, 2, 3, 4, 5, 6, 7, 9, 10]
Is aug: True
=> Parsing SemanticKITTI valid
parsing seq 08
Using 815 scans from sequences [8]
Is aug: False
=> Parsing SemanticKITTI test
parsing seq 11
parsing seq 12
parsing seq 13
parsing seq 14
parsing seq 15
parsing seq 16
parsing seq 17
parsing seq 18
parsing seq 19
parsing seq 20
parsing seq 21
Using 3901 scans from sequences [11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21]
Is aug: False
2023-07-21 16:24:53,594 -- => Loading network architecture...
2023-07-21 16:24:53,720 -- => Model Parameters: 23.069487 M
2023-07-21 16:24:53,720 -- => Loading network weights...
ignore weight of mistached shape in key sem_branch.conv1_block.spconv_layers.0.layers_in.0.weight
ignore weight of mistached shape in key sem_branch.conv1_block.spconv_layers.0.layers.0.weight
ignore weight of mistached shape in key sem_branch.conv1_block.spconv_layers.0.layers.3.weight
ignore weight of mistached shape in key sem_branch.conv2_block.spconv_layers.0.layers_in.0.weight
ignore weight of mistached shape in key sem_branch.conv2_block.spconv_layers.0.layers.0.weight
ignore weight of mistached shape in key sem_branch.conv2_block.spconv_layers.0.layers.3.weight
ignore weight of mistached shape in key sem_branch.conv3_block.spconv_layers.0.layers_in.0.weight
ignore weight of mistached shape in key sem_branch.conv3_block.spconv_layers.0.layers.0.weight
ignore weight of mistached shape in key sem_branch.conv3_block.spconv_layers.0.layers.3.weight
2023-07-21 16:24:53,891 -- => Model loaded at weights/weights_epoch_035.pth
2023-07-21 16:24:53,913 -- => Passing the network on the validation set...
0%| | 0/408 [00:00<?, ?it/s]
Traceback (most recent call last):
File "validate.py", line 151, in
main()
File "validate.py", line 142, in main
time_list = validate(model, dataset['val'], _cfg, logger, metrics)
File "validate.py", line 59, in validate
for t, (data, indices) in enumerate(tqdm(dset, ncols=100)):
File "/home/re/anaconda3/envs/SSCRS/lib/python3.7/site-packages/tqdm/std.py", line 1178, in iter
for obj in iterable:
File "/home/re/anaconda3/envs/SSCRS/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 363, in next
data = self._next_data()
File "/home/re/anaconda3/envs/SSCRS/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 989, in _next_data
return self._process_data(data)
File "/home/re/anaconda3/envs/SSCRS/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1014, in _process_data
data.reraise()
File "/home/re/anaconda3/envs/SSCRS/lib/python3.7/site-packages/torch/_utils.py", line 395, in reraise
raise self.exc_type(msg)
IndexError: Caught IndexError in DataLoader worker process 0.
Original Traceback (most recent call last):
File "/home/re/anaconda3/envs/SSCRS/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 185, in _worker_loop
data = fetcher.fetch(index)
File "/home/re/anaconda3/envs/SSCRS/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
data = [self.dataset[idx] for idx in possibly_batched_index]
File "/home/re/anaconda3/envs/SSCRS/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in
data = [self.dataset[idx] for idx in possibly_batched_index]
File "/media/re/2384a6b4-4dae-400d-ad72-9b7044491b55/SSC_LiDAR/SSC_RS/SSC-RS/datasets/semantic_kitti.py", line 217, in getitem
return self.get_data(idx, flip_type), idx
File "/media/re/2384a6b4-4dae-400d-ad72-9b7044491b55/SSC_LiDAR/SSC_RS/SSC-RS/datasets/semantic_kitti.py", line 124, in get_data
scan_data = np.fromfile(self.filepaths[typ][idx], dtype=np.uint16)
IndexError: list index out of range

**Comment by shenxiaowrj** [comment]
And when I use the data represented by 2 only,I meet the below bug.

**Comment by shenxiaowrj** [comment]
And when I use the data represented by 1 only,I meet the below bug.
2023-07-21 16:24:53,337 -- ============ Validation weights: "weights/weights_epoch_035.pth" ============

=> Parsing SemanticKITTI train
parsing seq 00
parsing seq 01
parsing seq 02
parsing seq 03
parsing seq 04
parsing seq 05
parsing seq 06
parsing seq 07
parsing seq 09
parsing seq 10
Using 3834 scans from sequences [0, 1, 2, 3, 4, 5, 6, 7, 9, 10]
Is aug: True
=> Parsing SemanticKITTI valid
parsing seq 08
Using 815 scans from sequences [8]
Is aug: False
=> Parsing SemanticKITTI test
parsing seq 11
parsing seq 12
parsing seq 13
parsing seq 14
parsing seq 15
parsing seq 16
parsing seq 17
parsing seq 18
parsing seq 19
parsing seq 20
parsing seq 21
Using 3901 scans from sequences [11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21]
Is aug: False
2023-07-21 16:24:53,594 -- => Loading network architecture...
2023-07-21 16:24:53,720 -- => Model Parameters: 23.069487 M
2023-07-21 16:24:53,720 -- => Loading network weights...
ignore weight of mistached shape in key sem_branch.conv1_block.spconv_layers.0.layers_in.0.weight
ignore weight of mistached shape in key sem_branch.conv1_block.spconv_layers.0.layers.0.weight
ignore weight of mistached shape in key sem_branch.conv1_block.spconv_layers.0.layers.3.weight
ignore weight of mistached shape in key sem_branch.conv2_block.spconv_layers.0.layers_in.0.weight
ignore weight of mistached shape in key sem_branch.conv2_block.spconv_layers.0.layers.0.weight
ignore weight of mistached shape in key sem_branch.conv2_block.spconv_layers.0.layers.3.weight
ignore weight of mistached shape in key sem_branch.conv3_block.spconv_layers.0.layers_in.0.weight
ignore weight of mistached shape in key sem_branch.conv3_block.spconv_layers.0.layers.0.weight
ignore weight of mistached shape in key sem_branch.conv3_block.spconv_layers.0.layers.3.weight
2023-07-21 16:24:53,891 -- => Model loaded at weights/weights_epoch_035.pth
2023-07-21 16:24:53,913 -- => Passing the network on the validation set...
  0%|                                                                       | 0/408 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "validate.py", line 151, in <module>
    main()
  File "validate.py", line 142, in main
    time_list = validate(model, dataset['val'], _cfg, logger, metrics)
  File "validate.py", line 59, in validate
    for t, (data, indices) in enumerate(tqdm(dset, ncols=100)):
  File "/home/re/anaconda3/envs/SSCRS/lib/python3.7/site-packages/tqdm/std.py", line 1178, in __iter__
    for obj in iterable:
  File "/home/re/anaconda3/envs/SSCRS/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 363, in __next__
    data = self._next_data()
  File "/home/re/anaconda3/envs/SSCRS/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 989, in _next_data
    return self._process_data(data)
  File "/home/re/anaconda3/envs/SSCRS/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1014, in _process_data
    data.reraise()
  File "/home/re/anaconda3/envs/SSCRS/lib/python3.7/site-packages/torch/_utils.py", line 395, in reraise
    raise self.exc_type(msg)
IndexError: Caught IndexError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/re/anaconda3/envs/SSCRS/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 185, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/re/anaconda3/envs/SSCRS/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/re/anaconda3/envs/SSCRS/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/media/re/2384a6b4-4dae-400d-ad72-9b7044491b55/SSC_LiDAR/SSC_RS/SSC-RS/datasets/semantic_kitti.py", line 217, in __getitem__
    return self.get_data(idx, flip_type), idx
  File "/media/re/2384a6b4-4dae-400d-ad72-9b7044491b55/SSC_LiDAR/SSC_RS/SSC-RS/datasets/semantic_kitti.py", line 124, in get_data
    scan_data = np.fromfile(self.filepaths[typ][idx], dtype=np.uint16)
IndexError: list index out of range

**Comment by loki369loki** [comment]
And when I use the data represented by 2 only,I meet the below bug.

2023-07-21 16:28:14,617 -- ============ Validation weights: "weights/weights_epoch_035.pth" ============

=> Parsing SemanticKITTI train
parsing seq 00
parsing seq 01
parsing seq 02
parsing seq 03
parsing seq 04
parsing seq 05
parsing seq 06
parsing seq 07
parsing seq 09
parsing seq 10
Using 19130 scans from sequences [0, 1, 2, 3, 4, 5, 6, 7, 9, 10]
Is aug: True
=> Parsing SemanticKITTI valid
parsing seq 08
Using 4071 scans from sequences [8]
Is aug: False
=> Parsing SemanticKITTI test
parsing seq 11
parsing seq 12
parsing seq 13
parsing seq 14
parsing seq 15
parsing seq 16
parsing seq 17
parsing seq 18
parsing seq 19
parsing seq 20
parsing seq 21
Using 0 scans from sequences [11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21]
Is aug: False
2023-07-21 16:28:15,625 -- => Loading network architecture...
2023-07-21 16:28:15,757 -- => Model Parameters: 23.069487 M
2023-07-21 16:28:15,757 -- => Loading network weights...
ignore weight of mistached shape in key sem_branch.conv1_block.spconv_layers.0.layers_in.0.weight
ignore weight of mistached shape in key sem_branch.conv1_block.spconv_layers.0.layers.0.weight
ignore weight of mistached shape in key sem_branch.conv1_block.spconv_layers.0.layers.3.weight
ignore weight of mistached shape in key sem_branch.conv2_block.spconv_layers.0.layers_in.0.weight
ignore weight of mistached shape in key sem_branch.conv2_block.spconv_layers.0.layers.0.weight
ignore weight of mistached shape in key sem_branch.conv2_block.spconv_layers.0.layers.3.weight
ignore weight of mistached shape in key sem_branch.conv3_block.spconv_layers.0.layers_in.0.weight
ignore weight of mistached shape in key sem_branch.conv3_block.spconv_layers.0.layers.0.weight
ignore weight of mistached shape in key sem_branch.conv3_block.spconv_layers.0.layers.3.weight
2023-07-21 16:28:15,930 -- => Model loaded at weights/weights_epoch_035.pth
2023-07-21 16:28:15,954 -- => Passing the network on the validation set...
  0%|                                                                      | 0/2036 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "validate.py", line 151, in <module>
    main()
  File "validate.py", line 142, in main
    time_list = validate(model, dataset['val'], _cfg, logger, metrics)
  File "validate.py", line 59, in validate
    for t, (data, indices) in enumerate(tqdm(dset, ncols=100)):
  File "/home/re/anaconda3/envs/SSCRS/lib/python3.7/site-packages/tqdm/std.py", line 1178, in __iter__
    for obj in iterable:
  File "/home/re/anaconda3/envs/SSCRS/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 363, in __next__
    data = self._next_data()
  File "/home/re/anaconda3/envs/SSCRS/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 989, in _next_data
    return self._process_data(data)
  File "/home/re/anaconda3/envs/SSCRS/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1014, in _process_data
    data.reraise()
  File "/home/re/anaconda3/envs/SSCRS/lib/python3.7/site-packages/torch/_utils.py", line 395, in reraise
    raise self.exc_type(msg)
IndexError: Caught IndexError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/re/anaconda3/envs/SSCRS/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 185, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/re/anaconda3/envs/SSCRS/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/re/anaconda3/envs/SSCRS/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/media/re/2384a6b4-4dae-400d-ad72-9b7044491b55/SSC_LiDAR/SSC_RS/SSC-RS/datasets/semantic_kitti.py", line 217, in __getitem__
    return self.get_data(idx, flip_type), idx
  File "/media/re/2384a6b4-4dae-400d-ad72-9b7044491b55/SSC_LiDAR/SSC_RS/SSC-RS/datasets/semantic_kitti.py", line 124, in get_data
    scan_data = np.fromfile(self.filepaths[typ][idx], dtype=np.uint16)
IndexError: list index out of range

**Comment by shenxiaowrj** [comment]
I debug and find this issue,
![image](https://github.com/Jieqianyu/SSC-RS/assets/100119921/ba9f1ae2-3070-404c-9498-b2d4c1628d0a)
how can I solve it?

**Comment by Jieqianyu** [comment]
Thanks for your interest in our work.  The data represented 2 is required. After downloading and unzipping the data, please use the `label_downsample.py` script in the `datasets` directory to process the labels. We hope this helps you.

**Comment by loki369loki** [comment]
> 

Thank you so much. I will try it soon.
